### ISSUE TITLE
does not work well with metalsmith-watch

### ISSUE THREAD

**Issue by waozixyz** [fephil/metalsmith-metadata-directory#17]
the initial start up works fine, however once any file has changed and metalsmith-watch rebuilds the files that have changes i get the continues error:
```
Error: Duplicate file name: file.yml
```

**Comment by phildotdev** [comment]
Hi there. I don’t use metalsmith-watch in my workflow but I’ll look into this when I have some free time. I’m currently away without a laptop so it might be some time. 

Thanks.

**Comment by phildotdev** [comment]
Hello @spaceywolfi,

Sincere apologies for taking so long to get back to you about this. I've taken a look at metalsmith-watch and I can't resolve the problem. metalsmith-watch is not something I would personally use so this is up for grabs for someone else to attempt to solve.

Sorry I haven't provided a fix.

**Comment by waozixyz** [comment]
@fephil hey dont worry about it, but thanks for replying! :D
